In [1]:
import numpy as np


In [2]:
# create a 1D array
x = np.array([0, 1, 2, 3, 4, 5, 6])

In [3]:
# find all non-zero elements in x
def findNonZero(x):
    a = x[x != 0]
    return a
findNonZero(x)

array([1, 2, 3, 4, 5, 6])

In [4]:
# create a 5x5 matrix A with random numbers
A = np.random.randn(5, 5)

# create a 5x5 identity matrix B
B = np.eye(5)
print(A)
print(B)

[[-0.6933261   0.42728827 -0.4544107  -0.29317706 -1.44537083]
 [-0.33231718 -0.53573666 -1.39326016  0.79634948 -1.88545178]
 [ 0.43463402 -2.4882367   0.24023996 -0.25921024 -1.46509855]
 [-1.64466033  1.26556106  1.2358654  -1.00952331  0.7633682 ]
 [-0.3079603  -0.58569177 -0.51834346 -1.00445401 -0.11022182]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
# calculate the following equations
addProduct = np.add(A,B)
subtractProdcut = np.subtract(A,B)
matrixProduct = np.dot(A,B) #(matrix product)
# A' (transpose of A)
A_T= np.transpose(A)#transpose of A

print(A_T)

[[-0.6933261  -0.33231718  0.43463402 -1.64466033 -0.3079603 ]
 [ 0.42728827 -0.53573666 -2.4882367   1.26556106 -0.58569177]
 [-0.4544107  -1.39326016  0.24023996  1.2358654  -0.51834346]
 [-0.29317706  0.79634948 -0.25921024 -1.00952331 -1.00445401]
 [-1.44537083 -1.88545178 -1.46509855  0.7633682  -0.11022182]]


In [6]:
# calculate the mean, sum, max, min value for each column in A
A_min = A.min(axis= 0)
A_max = A.max(axis = 0)
A_sum = A.sum(axis = 0)
A_mean = A.mean(axis = 0)
A_analytic = [A_min, A_max, A_sum, A_mean]
print ("  MIN VALUE,          MAX VALUE,          SUM VALUE,            MEAN VALUE")
for w,x,y,z in zip(*A_analytic):
  print(w,x, y, z)

  MIN VALUE,          MAX VALUE,          SUM VALUE,            MEAN VALUE
-1.644660329032599 0.4346340191194725 -2.5436298920629037 -0.5087259784125807
-2.488236701766082 1.2655610590709927 -1.916815805352765 -0.383363161070553
-1.3932601629875196 1.2358653958897738 -0.889908976861846 -0.1779817953723692
-1.0095233075168701 0.7963494806625147 -1.7700151369079384 -0.3540030273815877
-1.8854517800743513 0.7633681979218218 -4.142774781752477 -0.8285549563504955


In [7]:
# normalize A with its max value A_max and min value A_min
# i.e., for any value x in A,
# x = (x - A_min) / (A_max - A_min)

def normalize(A):
    min = np.min(A)
    max = np.max(A)
    range = max - min
    return [(x-min)/range for x in A]
ypp = A
A_max = np.max(A)
A_min = np.min(A)
ypp = (ypp - A_min)/(A_max - A_min)
    
normalize_A = normalize(A)
normalize_A




[array([0.47815858, 0.77668675, 0.54180489, 0.58475703, 0.27781621]),
 array([0.57433023, 0.52013991, 0.29169833, 0.8750035 , 0.16058002]),
 array([0.77864363, 0.        , 0.72685766, 0.59380569, 0.27256081]),
 array([0.22472611, 1.        , 0.99208917, 0.39392463, 0.86621739]),
 array([0.58081882, 0.50683203, 0.52477341, 0.39527508, 0.63349574])]

In [8]:
# advanced exercise
# solve the system of equations:
#3 * x0 + x1 = 9
#x0 + 2 * x1 = 8

A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
Ax = b
inv_A = np.linalg.inv(A)
x

array([2., 3.])

In [9]:
# compare x with the product of inverse A and b

product = np.dot(inv_A,b)
print(x)
print(product)

#product of inverse A and b has the same matrix with x

[2. 3.]
[2. 3.]
